added video controller
Sulagna-Dutta-Roy/GGExtensions pull request #1287
Opened 2024-06-08 18:26 UTC by GAGGZ1

# Description

Implemented a Chrome extension for controlling the playback speed of videos on webpages. This resolves issue #123.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resources
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/81284966/2a12dae5-fcbc-4c08-a0cc-25b828d95a7a)

2024-06-08 18:28 UTC, GAGGZ1 commented
@Sulagna-Dutta-Roy i have resolved this issue please check it out and accept my PR

2024-06-08 19:56 UTC, Sulagna-Dutta-Roy requested changes
Change the directory name as: Video Speed Controller/your files 
Add the proper Issue no

2024-06-09 04:45 UTC, GAGGZ1 commented
@Sulagna-Dutta-Roy  i have changed please visit

2024-06-09 16:19 UTC, Sulagna-Dutta-Roy approved these changes

2024-06-09 16:19 UTC, merged