Add new feature: Catch_The_Falling_Object
Sulagna-Dutta-Roy/GGExtensions pull request #1372
Opened 2024-06-09 18:02 UTC by katarianikita2003

# Description
Add a new game Catch_The_Falling_Object

Fixes:  #1351 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X ] I have made this from my own
- [ X] I have taken help from some online resourses 
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/158465309/ce2b1d61-3f5a-4c9c-b3cf-a1c08d13d1ee

![Catch The Falling Objects 1](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/158465309/c5e7bf24-9913-4b70-be27-aafffd800258)

![Catch The Falling Objects 2](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/158465309/d52b3a97-3486-42c9-9fa5-b0b1a2902ad0)

2024-06-09 18:05 UTC, katarianikita2003 commented
@Sulagna-Dutta-Roy , Sorry, I delete my previous head repo by-mistake
So I Create a New PR
Sorry for this

2024-06-09 18:05 UTC, katarianikita2003 commented
Please review it

2024-06-09 19:29 UTC, Sulagna-Dutta-Roy requested changes
Change the directory name as: Catch The Falling Object/your files

2024-06-11 15:15 UTC, Sulagna-Dutta-Roy approved these changes

2024-06-11 15:15 UTC, merged