eyeCare - Protect your vision eyeCare - Protect your vision
Sulagna-Dutta-Roy/GGExtensions pull request #1378
Opened 2024-06-09 18:53 UTC by GAGGZ1

# Description

Fixes: #1305

## Summary of Change

This change addresses the issue #1305 by creating a Chrome extension named "eyeCare - Protect your vision." The extension notifies users to take breaks at regular intervals and provides eye and back exercises based on the 20-20-20 rule. It aims to reduce eye strain and lower back pain associated with prolonged computer use.

## Motivation and Context

Prolonged screen time can lead to eye strain, neck pain, and lower back discomfort, affecting the health and productivity of computer users. The "eyeCare - Protect your vision" extension offers a solution by reminding users to take breaks at intervals based on the 20-20-20 rule and providing exercises to alleviate strain and discomfort. By promoting healthy habits and providing relief measures, the extension aims to enhance the well-being and productivity of users who spend long hours in front of computers.

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resources 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

2024-06-09 19:42 UTC, Sulagna-Dutta-Roy requested changes
Can you please check why other projects also showing here?

2024-06-09 19:52 UTC, GAGGZ1 commented
ok

2024-06-09 20:40 UTC, GAGGZ1 commented
@Sulagna-Dutta-Roy  i have review and requested Pull request kindly visit

2024-06-10 13:57 UTC, Sulagna-Dutta-Roy approved these changes

2024-06-10 13:57 UTC, merged