zombies game
Sulagna-Dutta-Roy/GGExtensions pull request #1451
Opened 2024-06-10 19:11 UTC by taneeshaa15

Hi @Sulagna-Dutta-Roy ,
I hope you're doing well. I've addressed the issue #1434  and created a pull request to resolve it.
Could you please review the PR and let me know if any adjustments are needed?

Best regards,
Tanisha Garg

2024-06-10 20:00 UTC, Sulagna-Dutta-Roy requested changes
Kindly add manifest.json file

2024-06-11 10:05 UTC, taneeshaa15 commented
Updated the file, please review it now.

2024-06-11 16:47 UTC, taneeshaa15 commented
@Sulagna-Dutta-Roy All files added, kindly review

2024-06-11 17:05 UTC, Sulagna-Dutta-Roy approved these changes

2024-06-11 17:05 UTC, merged