Solved issue #1924- Physics simulation
Sulagna-Dutta-Roy/GGExtensions pull request #1939
Opened 2024-06-26 09:28 UTC by Aditi22Bansal

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(issue no.)
#1924 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Uploading Recording 2024-06-26 144545 (1).mp4…

2024-06-26 09:30 UTC, Aditi22Bansal commented
@Sulagna-Dutta-Roy 
Kindly review and merge
and also which kind of pr in your repo is marked as level 3 kindly tell

2024-06-26 20:15 UTC, Sulagna-Dutta-Roy requested changes
Add manifest files @Aditi22Bansal

2024-06-27 09:25 UTC, Aditi22Bansal commented
@Sulagna-Dutta-Roy 
Kindly review and approve

2024-06-27 21:12 UTC, Sulagna-Dutta-Roy approved these changes

2024-06-27 21:12 UTC, merged