ADDED SPACE SHIP GAME
Sulagna-Dutta-Roy/GGExtensions pull request #2280
Opened 2024-07-10 07:37 UTC by TheNikhilRaj

# Description

Spaceship-Game
Game is fully playable! Enemies and teammates will spawn randomly on the map. The current aim is to survive for as long as you can but I will add score and win conditions later. Ships will drop resources when killed. Shooting and using abilities will now consume resources. Shield is the blue bar at the top and health is the grey bar below the shield bar.

press 'start' to start the game.

W to accelerate

S to decelerate

A and D to rotate

Q to switch aiming mode

turrets follow mouse pointer

Left click to shoot turrets

E to shoot main cannon

F to fire railgun

hold down R to boost

X to repair (regenerate hp)

R to boost

U to open/close upgrades menu (and pause)

Save by clicking the save button in the upgrades menu

Zoom out to see more of the map at once

For the experimental version of the game which may or may not work:

Fixes:  #2250 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![Capture](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/129590267/32901de1-90a9-4fce-b31b-653943bf6446)

@Sulagna-Dutta-Roy

2024-07-10 18:59 UTC, Sulagna-Dutta-Roy requested changes
Where's manifest files? Reducing to level1 because the project looks like entry level with many pictures only @TheNikhilRaj

2024-07-11 04:07 UTC, TheNikhilRaj commented
@Sulagna-Dutta-Roy manifest file is already there Space "Ship Game/manifest.json" no it's not entry-level give level 2.

2024-07-11 13:09 UTC, Sulagna-Dutta-Roy commented
It's an entry level project I checked. And labels are defined already previously. Not every project is Intermediate. 
Contributors can say this but as an admin. Labels are predefined and dependent on many factors. 
Your other PRs are level 2.

2024-07-11 13:29 UTC, Sulagna-Dutta-Roy approved these changes

2024-07-11 13:29 UTC, merged