Added 2d distance calci
Sulagna-Dutta-Roy/GGExtensions pull request #2385
Opened 2024-07-14 02:00 UTC by pavitraag

# Description
Added 2D distance calci

Fixes:  #2362 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

2024-07-14 16:13 UTC, Sulagna-Dutta-Roy requested changes
Kindly add manifest files @pavitraag 


Contributions should be stopped after 150 points from my repo. Check the Issues section @pavitraag

2024-07-15 00:56 UTC, pavitraag commented
Done with changes @Sulagna-Dutta-Roy

2024-07-15 17:11 UTC, Sulagna-Dutta-Roy approved these changes

2024-07-15 17:11 UTC, merged

2024-07-24 14:29 UTC, sanjay-kv commented
![image](https://github.com/user-attachments/assets/ffdaa79a-a99f-403a-81fb-94f33477d0e7)