Added Review Aggregator Extension
Sulagna-Dutta-Roy/GGExtensions pull request #2585
Opened 2024-08-02 18:42 UTC by sreevidya-16

# Description

Added Review Aggregator Extension

Fixes:  #(issue no.)
Fixes #2525 issue

## Type of change

d)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

2024-08-02 18:42 UTC, sreevidya-16 commented
@Sulagna-Dutta-Roy, view this PR

2024-08-02 19:28 UTC, Sulagna-Dutta-Roy requested changes
Change the directory name: Review Aggregator/your files @sreevidya-16

2024-08-03 01:40 UTC, sreevidya-16 commented
Updated this PR @Sulagna-Dutta-Roy, once view this

2024-08-03 06:31 UTC, Sulagna-Dutta-Roy approved these changes

2024-08-03 06:31 UTC, merged