Add/dad jokes
Sulagna-Dutta-Roy/GGExtensions pull request #478
Opened 2024-05-24 18:30 UTC by harshmishra19

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

I've added a dad jokes extension that you can use whenever you're bored and want to refresh your mind with a new dad joke

Fixes:  #392 

## Type of change

- [ x] New feature (non-breaking change which adds functionality)

# Checklist:

- [ x] I have made this from my own
- [x ] I have taken help from some online resources 
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/115486960/f39f1072-69c2-484f-a32a-69b4ad2b1bdd

2024-05-25 17:24 UTC, Sulagna-Dutta-Roy requested changes
Kindly check your branch is showing two folders.

2024-05-26 04:32 UTC, harshmishra19 commented
yes i have made two PRs so thats why its showing two branch Dad jokes and weight calculator(from another issue)

2024-05-26 20:52 UTC, harshmishra19 commented
@Sulagna-Dutta-Roy ??

2024-05-26 21:33 UTC, Sulagna-Dutta-Roy approved these changes

2024-05-26 21:33 UTC, merged