fixes issue #424  now user can understand what he want to write in the barcode box
Sulagna-Dutta-Roy/GGExtensions pull request #490
Opened 2024-05-25 06:03 UTC by MohanaSrinivas

Fixes:  #424 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![Screenshot 2024-05-25 113006](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/128175768/afa30373-4d25-4a9d-bcaf-9c3cae4817d1)
![Screenshot 2024-05-25 113028](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/128175768/c4845bae-2c01-4a62-8103-22f313205dd2)

2024-05-25 17:29 UTC, Sulagna-Dutta-Roy requested changes
Delete the .vscode file

2024-05-25 17:43 UTC, MohanaSrinivas reviewed
Deleted the.vscode file

2024-05-26 16:01 UTC, Sulagna-Dutta-Roy approved these changes

2024-05-26 16:01 UTC, merged

2024-05-26 16:10 UTC, Sulagna-Dutta-Roy commented
One small advice for you: make some valuable changes that can Impact the project. Because big contribution also matters