gold silver price tracker added
Sulagna-Dutta-Roy/GGExtensions pull request #516
Opened 2024-05-27 16:20 UTC by Yashgabani845

# Description

i have fetched live gold and silver price from goldprice.ip api and shown in chrome extension 
it is shown in USD 
asnd it will change live and dynamuically

Fixes:  #507 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![Screenshot (128)](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/127788321/7a1dfdeb-ebb8-49df-a5e4-ad5fb14f5a03)

2024-05-27 16:21 UTC, Yashgabani845 commented
@Sulagna-Dutta-Roy  please Review this PR

2024-05-27 20:31 UTC, Sulagna-Dutta-Roy requested changes
Please change the directory name as: 
Gold Price Tracker/your files

2024-05-28 05:23 UTC, Yashgabani845 reviewed
@Sulagna-Dutta-Roy  chnaged folder name please check irt

2024-05-28 06:09 UTC, Sulagna-Dutta-Roy approved these changes

2024-05-28 06:09 UTC, merged