BMR calculator
Sulagna-Dutta-Roy/GGExtensions pull request #568
Opened 2024-05-30 18:04 UTC by harshmishra19

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

I have added a BMR calculator

Fixes:  #488 

## Type of change

- [x ] New feature (non-breaking change which adds functionality)

# Checklist:

- [x ] I have made this from my own
- [ x] I have taken help from some online resourses 
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/115486960/13d7aaf1-12b0-48f9-9e7c-8596dcd78b4a

2024-05-30 18:17 UTC, Sulagna-Dutta-Roy requested changes
Date and Time calculator is showing. Can you please check

2024-05-30 18:20 UTC, harshmishra19 commented
Yes actually after making date and time calculator PR I opened this PR that's why it's showing both

2024-05-31 13:25 UTC, Sulagna-Dutta-Roy commented
Kindly create one by one PRs for this type of issues. Last time I faced a severe problem for overwriting

2024-05-31 13:25 UTC, Sulagna-Dutta-Roy approved these changes

2024-05-31 13:25 UTC, merged