Contest Finder Extension added
Sulagna-Dutta-Roy/GGExtensions pull request #730
Opened 2024-06-02 12:00 UTC by Vipullakum007

# Description

i have added contest finder api that will give user to fututre contest .
user can register for that also.

Fixes:  #712 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Uploading ContestFinder.mp4…

2024-06-02 18:32 UTC, Sulagna-Dutta-Roy requested changes
Change the directory name as: Contest Finder Extension/your files

2024-06-03 01:25 UTC, Vipullakum007 commented
hey @Sulagna-Dutta-Roy , folder is renamed as per your suggestion.

2024-06-03 17:11 UTC, Sulagna-Dutta-Roy approved these changes

2024-06-03 17:12 UTC, merged

2024-06-27 04:30 UTC, sanjay-kv commented
@Vipullakum007 
![image](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/30715153/df8d2a54-24a4-47af-a02c-793aaf95c42b)
same with this