Added Degree-Radian Calculator: #757
Sulagna-Dutta-Roy/GGExtensions pull request #764
Opened 2024-06-02 19:39 UTC by Anshika14528

# Description
I have added a Degree-Radian Calculator which is used to convert angle from degree to radian and vice-versa.

Fixes:  #757 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x
<img width="1462" alt="Screenshot 2024-06-03 at 12 56 25 AM" src="https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/168436423/db70e9f1-c698-475d-bfce-b155d364e24a">
] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

2024-06-02 19:44 UTC, Sulagna-Dutta-Roy requested changes
Change the directory name as: Degree Radian Calculator/your files

2024-06-02 20:07 UTC, Anshika14528 commented
@Sulagna-Dutta-Roy mam , i have updated the name please review it now.

2024-06-03 17:09 UTC, Anshika14528 commented
@Sulagna-Dutta-Roy mam , please review it

2024-06-03 17:13 UTC, Sulagna-Dutta-Roy approved these changes

2024-06-03 17:13 UTC, merged