Added Company Portfolio Extension
Sulagna-Dutta-Roy/GGExtensions pull request #875
Opened 2024-06-04 17:29 UTC by Ayushmaanagarwal1211

# Description

I've added the company portfolio extension 

Fixes:  #829 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

![Screenshot 2024-06-04 081143](https://github.com/Sulagna-Dutta-Roy/GGExtensions/assets/118350936/d080620e-504b-4ec0-aab4-222157bd1e60)

2024-06-04 18:58 UTC, Sulagna-Dutta-Roy requested changes
Kindly delete all the package dependencies including vendor folder.

2024-06-05 03:19 UTC, Ayushmaanagarwal1211 commented
@Sulagna-Dutta-Roy  i fixed it please review it again

2024-06-05 17:07 UTC, Sulagna-Dutta-Roy approved these changes

2024-06-05 17:08 UTC, merged

2024-06-05 17:09 UTC, Ayushmaanagarwal1211 commented
@Sulagna-Dutta-Roy  i want to ask one question can i also open issues for the projects that are already in repository .